[profile.default-miri]
slow-timeout = { period = "60s", terminate-after = 1 }
failure-output = "never"
status-level = "all"
final-status-level = "none"

[profile.default-miri.junit] 
path = "junit.xml"
store-failure-output = true
