[profile.default-miri]
slow-timeout = { period = "60s", terminate-after = 1 }
failure-output = "never"
status-level = "all"
final-status-level = "none"

[profile.default-miri.junit] 
path = "junit.xml"
store-failure-output = true

[profile.slow-miri]
slow-timeout = { period = "150s", terminate-after = 1 }
failure-output = "never"
status-level = "all"
final-status-level = "none"

[profile.slow-miri.junit] 
path = "junit.xml"
store-failure-output = true

# unfiltered timeouts were 1340 in 2275-3793 crates before deploying timeout doubling
